apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  replicas: 1
  serviceName: dispatcher
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
        - name: dispatcher
          image: DISPATCHER_IMAGE
          imagePullPolicy: IMAGE_PULL_POLICY
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/keys/google-credentials.json"
            - name: SERVICES_BQ_TABLE
              value: "SERVICES_BQ_TABLE_VALUE"
            - name: SERVICES_BQ_TABLE_REGION
              value: "SERVICES_BQ_TABLE_REGION_VALUE"
          volumeMounts:
            - name: google-credentials
              mountPath: "/etc/keys"
              readOnly: true
          livenessProbe:
            exec:
              command:
                - python3
                - /app/healthcheck.py
            initialDelaySeconds: 60
            periodSeconds: 180
      volumes:
        - name: google-credentials
          secret:
            secretName: keys
