---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dispatcher
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    resourceNames: ["worker"]
    verbs: ["update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dispatcher
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: dispatcher
  apiGroup: rbac.authorization.k8s.io
