apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: WORKER_IMAGE
          imagePullPolicy: IMAGE_PULL_POLICY
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/keys/google-credentials.json"
            - name: SERVICES_COLLECTION
              value: "SERVICES_COLLECTION_VALUE"
            - name: FIRST_EMAIL_TOPIC
              value: "FIRST_EMAIL_TOPIC_VALUE"
          volumeMounts:
            - name: google-credentials
              mountPath: "/etc/keys"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: google-credentials
          secret:
            secretName: keys
