name: Deploy cloud functions source code to prod components

on:
  push:
    branches: ["main"]
    paths: ["cloud-functions/**"]

env:
  REGION: europe-central2
  EMAILS_SENT_COLLECTION: emails_sent
  GCP_PROJECT: irio-solution
  EMAIL_QUEUE: second-email
  SECRETS: "ACK_ENDPOINT=ACK_ENDPOINT_PROD:latest,\
    EMAIL_SENDER=EMAIL_SENDER:latest,\
    SENDGRID_API_KEY=SENDGRID_API_KEY:latest,\
    TWILIO_ACCOUNT_SID=TWILIO_ACCOUNT_SID:latest,\
    TWILIO_AUTH_TOKEN=TWILIO_AUTH_TOKEN:latest,\
    TWILIO_NUMBER=TWILIO_NUMBER:latest,\
    GCP_PROJECT=GCP_PROJECT:latest,\
    EMAIL_COLLECTION=EMAIL_COLLECTION_PROD:latest,\
    EMAIL_QUEUE=EMAIL_QUEUE_PROD:latest,\
    REGION=GCP_REGION:latest,\
    SECOND_SENDER_ENDPOINT=SECOND_SENDER_ENDPOINT_PROD:latest"

jobs:
  deploy_cloud_functions_src_code:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/7432286469/locations/global/workloadIdentityPools/default-pool/providers/gh-provider"
          service_account: "gh-service-account@irio-solution.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - id: "deploy_first_sender"
        run: |-
          gcloud functions deploy first-sender \
          --gen2 \
          --runtime=python310 \
          --region=$REGION \
          --memory=256Mi \
          --source='cloud-functions/first-sender' \
          --entry-point='save_send_query_event' \
          --trigger-topic='first-email'

      - id: "deploy_second_sender"
        run: |-
          gcloud functions deploy second-sender \
          --gen2 \
          --runtime=python310 \
          --region=$REGION \
          --memory=256Mi \
          --source='cloud-functions/second-sender' \
          --entry-point='check_send_event' \
          --trigger-http

      - id: "deploy_ack_endpoint"
        run: |-
          gcloud functions deploy ack-endpoint \
          --set-env-vars EMAILS_SENT_COLLECTION=$EMAILS_SENT_COLLECTION \
          --gen2 \
          --runtime=python310 \
          --region=$REGION \
          --memory=256Mi \
          --source='cloud-functions/ack-endpoint' \
          --entry-point='handle_request'

    # Example of using the output

#     - id: 'test'
#       run: 'curl "${{ steps.deploy.outputs.url }}"'
