name: Deploy cloud functions source code to test components

on:
  push:
    branches: ["test"]
    paths: ["cloud-functions/**"]

env:
  REGION: europe-central2
  EMAILS_SENT_COLLECTION: emails_sent_test

jobs:
  deploy_cloud_functions_src_code_to_test:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/7432286469/locations/global/workloadIdentityPools/default-pool/providers/gh-provider"
          service_account: "gh-service-account@irio-solution.iam.gserviceaccount.com"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

#     - id: 'deploy_sender1'
#       uses: 'google-github-actions/deploy-cloud-functions@v1'
#       with:
#         name: 'first-sender'
#         runtime: 'python310'
#         entry_point: 'handle_first_email'
#         memory_mb: 128
#         region: 'europe-central2'
#         source_dir: 'cloud-functions/first-sender'
    
#     - id: 'deploy_sender2'
#       uses: 'google-github-actions/deploy-cloud-functions@v1'
#       with:
#         name: 'second-sender'
#         runtime: 'python310'
#         entry_point: 'handle_second_email'
#         memory_mb: 128
#         region: 'europe-central2'
#         source_dir: 'cloud-functions/second-sender'
    
#     - id: 'deploy_ack_endpoint'
#       uses: 'google-github-actions/deploy-cloud-functions@v1'
#       with:
#         name: 'ack-endpoint'
#         runtime: 'python310'
#         entry_point: 'handle_request'
#         memory_mb: 128
#         region: 'europe-central2'
#         source_dir: 'cloud-functions/ack-endpoint'

      - id: 'deploy_ack_endpoint_test'
        run: |-
          gcloud functions deploy ack-endpoint-test \
          --set-env-vars EMAILS_SENT_COLLECTION=$EMAILS_SENT_COLLECTION \
          --gen2 \
          --runtime=python310 \
          --region=$REGION \
          --memory=256Mi \
          --source='cloud-functions/ack-endpoint' \
          --entry-point='handle_request'

    # Example of using the output
#     - id: 'test'
#       run: 'curl "${{ steps.deploy.outputs.url }}"'
