name: Deploy cloud functions source code to test components

on:
  push:
    branches: ["test"]
    paths: ["cloud-functions/**"]

env:
  REGION: europe-central2
  EMAILS_SENT_COLLECTION: emails_sent_test

jobs:
  deploy_cloud_functions_src_code_to_test:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/7432286469/locations/global/workloadIdentityPools/default-pool/providers/gh-provider"
          service_account: "gh-service-account@irio-solution.iam.gserviceaccount.com"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: 'deploy_first_sender'
        run: |-
          gcloud functions deploy first-sender-test \
          --gen2 \
          --runtime=python310 \
          --region=$REGION \
          --memory=256Mi \
          --source='cloud-functions/first-sender' \
          --entry-point='save_send_query_event' \
          --trigger-topic=first-email-test'

      #  TODO: finish second sender deployment
      # - id: "deploy_second_sender"
      #   run: |-
      #     gcloud functions deploy second-sender-test \
      #     --gen2 \
      #     --runtime=python310 \
      #     --region=$REGION \
      #     --memory=256Mi \
      #     --source='cloud-functions/second-sender' \
      #     --entry-point='save_send_query_event'

      - id: 'deploy_ack_endpoint'
        run: |-
          gcloud functions deploy ack-endpoint-test \
          --set-env-vars EMAILS_SENT_COLLECTION=$EMAILS_SENT_COLLECTION \
          --gen2 \
          --runtime=python310 \
          --region=$REGION \
          --memory=256Mi \
          --source='cloud-functions/ack-endpoint' \
          --entry-point='handle_request'
