# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when there is a push to the "main" branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Create and configure a Workload Identity Provider for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Change the values for the GAR_LOCATION, GKE_ZONE, GKE_CLUSTER, IMAGE, REPOSITORY and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke-kustomize

name: Build and Deploy to GKE

on:
  push:
    branches: [ "main" ]
    paths: [ "worker-k8s/**" ]

env:
  PROJECT_ID: irio-solution
  GAR_LOCATION: europe-central2 # region of the Artifact Registry
  GKE_CLUSTER: autopilot-cluster-1    # TODO: update to cluster name
  GKE_ZONE: europe-central2   # TODO: update to cluster zone
  DEPLOYMENT_NAME: dispatcher # TODO: update to deployment name
  REPOSITORY: k8s-docker-images # TODO: update to Artifact Registry docker repository
  IMAGE1: dispatcher
  IMAGE2: worker

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/7432286469/locations/global/workloadIdentityPools/default-pool/providers/gh-provider'
        service_account: 'gh-service-account@irio-solution.iam.gserviceaccount.com'

    # Alternative option - authentication via credentials json
    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v0'
    #   with:
    #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev
    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the worker Docker image
    - name: Build dispatcher
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE1:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          worker-k8s/dispatcher
        # Build the worker Docker image
    - name: Build Worker
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE2:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          worker-k8s/worker
    # Push the Docker image to Google Artifact Registry
    - name: Publish Dispatcher
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE1:$GITHUB_SHA"
    - name: Publish Worker
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE2:$GITHUB_SHA"
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        # replacing the image name etc. in the k8s template
        ls -hal
        sed "s,IMAGE_PULL_POLICY,Always,g" ./worker-k8s/deploy/worker-deployment.yaml > worker-deployment.yaml
        sed -i "s,WORKER_IMAGE,$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE2:$GITHUB_SHA,g" worker-deployment.yaml
        sed "s,IMAGE_PULL_POLICY,Always,g" ./worker-k8s/deploy/dispatcher-deployment.yaml > dispatcher-deployment.yaml
        sed -i "s,DISPATCHER_IMAGE,$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE1:$GITHUB_SHA,g" dispatcher-deployment.yaml
        ls -hal
        kubectl apply -f worker-deployment.yaml
        kubectl apply -f dispatcher-deployment.yaml
        kubectl apply -f ./worker-k8s/deploy/roles.yaml
        kubectl apply -f ./worker-k8s/deploy/hpa.yaml
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
