name: Build and push the test to the registry
on:
  push:
    branches: [ "main"]
    paths: ["testing/**"]

env:
  REGION: europe-central2


jobs:
  build-push:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/7432286469/locations/global/workloadIdentityPools/default-pool/providers/gh-provider'
        service_account: 'gh-service-account@irio-solution.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Build and Push'
      run: |-
        cd testing
        gcloud builds submit --pack image=gcr.io/irio-solution/cloud-functions-integration-test
        cd ..

